name: PR Test
on:
  pull_request:
    types: [opened, reopened, synchronize]
env:
  JSONBLOB_ID: ${{ secrets.JSONBLOB_ID }}
jobs:
  test-pr:
    runs-on: ubuntu-latest
    name: Test pr action
    steps:
      - name: Test Coverage
        uses: ScientaNL/coverage-actions@develop
        with:
          action_type: "read"
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.number }}
          repo: "coverage-actions"
          owner: "ScientaNL"
          lines_coverage: "6.10"
          method_coverage: "5.90"
          class_coverage: "6"
          storage_adapter: 'Jsonblob'
